'''
    Unittests/Chemical/Proteins/_data
    _________________________________

    Non-public module containing test data for protease
    and protein objects.

    :copyright: (c) 2015 The Regents of the University of California.
    :license: GNU GPL, see licenses/GNU GPLv3.txt for more details.
'''

# DATA
# ----


SEQUENCES = [
    'MKWVTFISLLLLFSSAYSRGVFRRDTHKSEIAHRFKDLGEEHFKGLVLIAFSQYLQQCPF'
    'DEHVKLVNELTEFAKTCVADESHAGCEKSLHTLFGDELCKVASLRETYGDMADCCEKQEP'
    'ERNECFLSHKDDSPDLPKLKPDPNTLCDEFKADEKKFWGKYLYEIARRHPYFYAPELLYY'
    'ANKYNGVFQECCQAEDKGACLLPKIETMREKVLASSARQRLRCASIQKFGERALKAWSVA'
    'RLSQKFPKAEFVEVTKLVTDLTKVHKECCHGDLLECADDRADLAKYICDNQDTISSKLKE'
    'CCDKPLLEKSHCIAEVEKDAIPENLPPLTADFAEDKDVCKNYQEAKDAFLGSFLYEYSRR'
    'HPEYAVSVLLRLAKEYEATLEECCAKDDPHACYSTVFDKLKHLVDEPQNLIKQNCDQFEK'
    'LGEYGFQNALIVRYTRKVPQVSTPTLVEVSRSLGKVGTRCCTKPESERMPCTEDYLSLIL'
    'NRLCVLHEKTPVSEKVTKCCTESLVNRRPCFSALTPDETYVPKAFDEKLFTFHADICTLP'
    'DTEKQIKKQTALVELLKHKPKATEEQLKTVMENFVAFVDKCCAADDKEACFAVEGPKLVV'
    'STQTALA',

    'MVKVGVNGFGRIGRLVTRAAFNSGKVDVVAINDPFIDLHYMVYMFQYDSTHGKFHGTVKA'
    'ENGKLVINGKAITIFQERDPANIKWGDAGAEYVVESTGVFTTMEKAGAHLKGGAKRVIIS'
    'APSADAPMFVMGVNHEKYDNSLKIVSNASCTTNCLAPLAKVIHDHFGIVEGLMTTVHAIT'
    'ATQKTVDGPSGKLWRDGRGAAQNIIPASTGAAKAVGKVIPELNGKLTGMAFRVPTPNVSV'
    'VDLTCRLEKAAKYDDIKKVVKQASEGPLKGILGYTEDQVVSCDFNSATHSSTFDAGAGIA'
    'LNDHFVKLISWYDNEFGYSNRVVDLMVHMASKE'
]

# ITEMS
# -----

LENGTHS = [
    607,
    333
]

MOLECULAR_WEIGHTS = [
    69248.4406831678,
    35757.2476412281
]

REVERSED = [
    'ALATQTSVVLKPGEVAFCAEKDDAACCKDVFAVFNEMVTKLQEETAKPKH'
    'KLLEVLATQKKIQKETDPLTCIDAHFTFLKEDFAKPVYTEDPTLASFCPR'
    'RNVLSETCCKTVKESVPTKEHLVCLRNLILSLYDETCPMRESEPKTCCRT'
    'GVKGLSRSVEVLTPTSVQPVKRTYRVILANQFGYEGLKEFQDCNQKILNQ'
    'PEDVLHKLKDFVTSYCAHPDDKACCEELTAEYEKALRLLVSVAYEPHRRS'
    'YEYLFSGLFADKAEQYNKCVDKDEAFDATLPPLNEPIADKEVEAICHSKE'
    'LLPKDCCEKLKSSITDQNDCIYKALDARDDACELLDGHCCEKHVKTLDTV'
    'LKTVEVFEAKPFKQSLRAVSWAKLAREGFKQISACRLRQRASSALVKERM'
    'TEIKPLLCAGKDEAQCCEQFVGNYKNAYYLLEPAYFYPHRRAIEYLYKGW'
    'FKKEDAKFEDCLTNPDPKLKPLDPSDDKHSLFCENREPEQKECCDAMDGY'
    'TERLSAVKCLEDGFLTHLSKECGAHSEDAVCTKAFETLENVLKVHEDFPC'
    'QQLYQSFAILVLGKFHEEGLDKFRHAIESKHTDRRFVGRSYASSFLLLLS'
    'IFTVWKM',

    'EKSAMHVMLDVVRNSYGFENDYWSILKVFHDNLAIGAGADFTSSHTASNF'
    'DCSVVQDETYGLIGKLPGESAQKVVKKIDDYKAAKELRCTLDVVSVNPTP'
    'VRFAMGTLKGNLEPIVKGVAKAAGTSAPIINQAAGRGDRWLKGSPGDVTK'
    'QTATIAHVTTMLGEVIGFHDHIVKALPALCNTTCSANSVIKLSNDYKEHN'
    'VGMVFMPADASPASIIVRKAGGKLHAGAKEMTTFVGTSEVVYEAGADGWK'
    'INAPDREQFITIAKGNIVLKGNEAKVTGHFKGHTSDYQFMYVMYHLDIFP'
    'DNIAVVDVKGSNFAARTVLRGIRGFGNVGVKVM',
]
